// <auto-generated />
using System;
using Lab_18;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab_18.Migrations
{
    [DbContext(typeof(Lab18DB))]
    [Migration("20210604101807_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab_18.Airport", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaneTiketID")
                        .HasColumnType("int");

                    b.Property<int?>("PlaneTiketID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlaneTiketID");

                    b.HasIndex("PlaneTiketID1");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Lab_18.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birstdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaneTiketID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PlaneTiketID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Lab_18.PlaneTiket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimeDepart")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PlaneTikets");
                });

            modelBuilder.Entity("Lab_18.Airport", b =>
                {
                    b.HasOne("Lab_18.PlaneTiket", null)
                        .WithMany("ArrivePort")
                        .HasForeignKey("PlaneTiketID");

                    b.HasOne("Lab_18.PlaneTiket", null)
                        .WithMany("DepartPort")
                        .HasForeignKey("PlaneTiketID1");
                });

            modelBuilder.Entity("Lab_18.Person", b =>
                {
                    b.HasOne("Lab_18.PlaneTiket", null)
                        .WithMany("Person")
                        .HasForeignKey("PlaneTiketID");
                });

            modelBuilder.Entity("Lab_18.PlaneTiket", b =>
                {
                    b.Navigation("ArrivePort");

                    b.Navigation("DepartPort");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
